Lagrange.Core/Internal/Context/PacketContext.cs
Really excited to see dotnet projects of NTQQ&OneBot, fix some minor things while going through codes.
=> Minor fix: use .GetAwaiter.GetResult to avoid AggregateException

.github/workflows/Lagrange.OneBot-build.yml
- `win-x64`
- `win-x86`
- `linux-x64`
- `linux-arm`
- `linux-arm64`
- `osx-x64`
- `osx-arm64`
*use `PublishSingleFile` to avoid publishing a lot of files
=> add a workflow

.gitignore, Lagrange.Core.Test/Tests/WtLoginTest.cs, Lagrange.Core/Common/Interface/Api/BotExt.cs, Lagrange.Core/Internal/Context/Logic/Implementation/WtExchangeLogic.cs, Lagrange.Core/Message/MessageBuilder.cs, Lagrange.OneBot/LagrangeApp.cs
- Expose the qrcode url for the user
- Remove redundant await statements for methods
- MessageBuilder adds IMessageEntity to the chain directly
- Update `.gitignore`. ignore idea files and dotnet user settings
=> Several updates

Lagrange.OneBot/Utility/QrCodeHelper.cs
修复了 QrCode 在不支持颜色的终端中显示异常的情况
其实是将 https://github.com/eric2788/Lagrange.Core/blob/fd20a5aec81cacd56d60f3130cf057461300fd3f/Lagrange.OneBot/Utility/QrCodeHelper.cs#L30C52-L30C52 的代码 Copy 了一下
原作者表示更改太多了不好 pr
感谢 [@eric2788](https://github.com/eric2788)
=> Fix QrCode display anomaly in terminals that don't support colors

Lagrange.OneBot/Core/Message/Entity/ImageSegment.cs
```log
{"file":"file:\/\/\/C:\\server\\XCW\\res\\img\\foods\\\u6d77\u5357\u6930\u5b50\u9e21.jpg"}}]},"echo":{"seq":12}}
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
Unexpected error encountered while handling message.
System.IO.FileNotFoundException: Could not find file 'C:\server\XCW\res\img\foods\%E6%B5%B7%E5%8D%97%E6%A4%B0%E5%AD%90%E9%B8%A1.jpg'.
```
#69
=> Fix non-pure English path encoding problem

Lagrange.OneBot/Core/Entity/Message/OneBotGroupMsg.cs, Lagrange.OneBot/Core/Message/MessageService.cs, Lagrange.OneBot/Core/Operation/Message/MessageCommon.cs
1. CQ Code parse is implemented using regex
2. only `OneBotGroupMessageText` with `AutoEscape == true` will send raw message now
https://github.com/LagrangeDev/Lagrange.Core/blob/36144c8110acd1b9ed57ad4e449adaf0e8d431e4/Lagrange.OneBot/Core/Operation/Message/MessageCommon.cs#L73-L79
3. `raw_message` is provided, fixes #72
=> Support CQ Code

Lagrange.OneBot/Core/Operation/OperationService.cs
fix #71 
Not sure if I should change it this way.
=> Avoid program crashes due to json deserialization failure

.github/workflows/Lagrange.OneBot-docker-push.yml, Docker.md, Dockerfile, Lagrange.OneBot/Core/Network/LagrangeWebSvcCollection.cs, Lagrange.OneBot/LagrangeAppBuilder.cs, appsettings.onebot.json
此PR有幾點需要注意:
- ~~[Lagrange.OneBot-docker-push.yml](https://github.com/LagrangeDev/Lagrange.Core/compare/master...eric2788:Lagrange.Core:feature/docker?expand=1#diff-b2012289e932ce38f4b7bc9ecfc9a678b8dcb50162504f46b9255d7b8b967d89) 需要 `${{ secrets.DOCKER_USERNAME }}` 和 `${{ secrets.DOCKER_PASSWORD }}` 方可生效~~ 已轉用 github docker registry
- ~~目前的 Dockerfile 有 30% 概率會出現 `failed unexpectedly`, 再跑一次通常就能成功運行，目前原因未知~~ 應該修好了
- `appsettings.json` 采用 array 的原因是因爲容易讓 docker 透過 環境參數 進行操作
- `Lagrange.OneBot/Core/Network/LagrangeWebSvcCollection.cs` 新增 `section["Enable"]` 是爲了方便透過 docker 設置 環境參數 選擇使用哪個服務。注意：此改動是很久以前改的，新改動之後尚未知道有無兼容問題
=> Added Docker Support

Lagrange.Core/Utility/ImageResolver.cs
Notice the following code
https://github.com/LagrangeDev/Lagrange.Core/blob/adaad5698b753dab911c7ce9baa3687411950be0/Lagrange.Core/Utility/ImageResolver.cs#L17-L33
Predicate for `JFIF` header is removed in this PR since it is not necessary for JPEG files. It only needs to scan for `SOF` headers.
Additionally, `image.AsSpan()` is de-inlined to `ReadOnlySpan<byte>` for readability.
=> [Core] Improve ImageResolver

.github/workflows/Lagrange.Core-nuget-push.yml
fix can't execute Lagrange.Core-nuget-push.yml when push
=> fix can't-execute-Lagrange.Core-nuget-push.yml-when-push

Docker.md
```bash
pk5ls@host:~$ docker pull lagrangedev/lagrange.onebot:edge
Error response from daemon: pull access denied for lagrangedev/lagrange.onebot, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
pk5ls@host:~$ docker pull ghcr.io/lagrangedev/lagrange.onebot:edge
edge: Pulling from lagrangedev/lagrange.onebot
Digest: sha256:ef1d20321b5347fc669d1911194905e01e36a75a4e029c77497a3819cbf624b8
Status: Image is up to date for ghcr.io/lagrangedev/lagrange.onebot:edge
ghcr.io/lagrangedev/lagrange.onebot:edge
```
=> [OneBot] Specify container image hosting in `Docker.md` as `ghcr.io`

README.md, README_zh.md
Cannot stand that rendering of markdown table with empty header, use raw HTML table instead.
=> Fix README navigator

Lagrange.OneBot/Core/Entity/Message/OneBotNode.cs, Lagrange.OneBot/Core/Operation/Message/GetForwardMsgOperation.cs
该pr需要被讨论！
当前`get_forward_msg`既不符合OneBot v11标准，也不符合常用的gocq事实标准
此Pr是为了符合ob11标准
[OneBot 11](https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9)
在example中展示了，user_id的类型应该为string
[GOCQ](https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E5%86%85%E5%AE%B9)
在example中展示了，user_id与nickname应包含在sender里，且user_id为int
=> [OneBot] Modify OneBotNode user_id type to be OneBot v11 compliant

Lagrange.OneBot/Core/Operation/Message/GetGroupMessageHistoryOperation.cs
=> [OneBot] Fix `count` parameter of `get_group_msg_history` not working as expected

Lagrange.OneBot/Core/Operation/Message/SendGroupMessageOperation.cs, Lagrange.OneBot/Core/Operation/Message/SendMessageOperation.cs, Lagrange.OneBot/Core/Operation/Message/SendPrivateForwardOperation.cs, Lagrange.OneBot/Core/Operation/Message/SendPrivateMessageOperation.cs, Lagrange.OneBot/Message/MessageService.cs
Fix #276 
The problem of not saving to the database exists only when private message is sent, so there is no need to save to the database when group message is sent.
Cannot modify some of the parameters of MessageChain, so new MessageRecord is used.
Can't get the signature of the Bot, use string.Empty for now.
=> [OneBot] Fix sender of get_msg incorrect for certain conditions

Lagrange.OneBot/Message/Entity/CommonResolver.cs
Change the image file read permission mode to `FileShare.Read`
```log
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
Unexpected error encountered while handling message.
System.IO.IOException: The process cannot access the file 'E:\Server\*\32860d5e-c3c0-4ff0-89be-f4613ada188a.jpg' because it is being used by another process.
at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, …
```
=> Solve image reading error under multiple bots

Lagrange.OneBot/Core/Network/Options/HttpPostServiceOptions.cs, Lagrange.OneBot/Core/Network/Options/WSServiceOptions.cs, Lagrange.OneBot/Core/Network/Service/ForwardWSService.cs, Lagrange.OneBot/Core/Network/Service/HttpPostService.cs, Lagrange.OneBot/Core/Network/Service/ReverseWSService.cs, README.md, README_zh.md
Details about this commit:
﻿
1. ForwardWSService now won't sending ultra fast heartbeat when HeartBeatInterval == 0.
2. Following [OneBot v11 protocol](https://github.com/botuniverse/onebot-11/blob/master/event/meta.md#%E7%9B%B8%E5%85%B3%E9%85%8D%E7%BD%AE), add option `HeartBeatEnable` to make options more user-friendly.
3. Following [OneBot v11 protocol](https://github.com/botuniverse/onebot-11/blob/master/event/meta.md#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F), ReverseWSService now also sending Connect Lifecycle MetaEvent.
4. ReverseWSService and HTTP POST now use more precise heartbeat intervals.
5. Project readme documents updated.
﻿
**This commit is compatible with past network services**. If this pull request accepted, I'll also open a pull request to update `Lagrange.Doc` .
=> [OneBot] Better and compatible supports for Network Services.

Lagrange.Core/Internal/Context/Uploader/ImageUploader.cs, Lagrange.Core/Internal/Context/Uploader/PttUploader.cs, Lagrange.Core/Internal/Context/Uploader/VideoUploader.cs, Lagrange.Core/Internal/Service/Message/ImageGroupUploadService.cs, Lagrange.Core/Internal/Service/Message/ImageUploadService.cs, Lagrange.Core/Internal/Service/Message/RecordGroupUploadService.cs, Lagrange.Core/Internal/Service/Message/RecordUploadService.cs, Lagrange.Core/Internal/Service/Message/VideoGroupUploadService.cs, Lagrange.Core/Internal/Service/Message/VideoUploadService.cs, Lagrange.Core/Message/Entity/ImageEntity.cs, Lagrange.Core/Message/Entity/RecordEntity.cs, Lagrange.Core/Message/Entity/VideoEntity.cs, Lagrange.OneBot/Message/Entity/ImageSegment.cs
Make stream initialization lazy, reducing overhead of message record deserialization & resolving possible `FileNotFoundException` & avoid unclosed stream
fixes #290
=> [Core] lazy initialization of streams

Lagrange.OneBot/Core/Network/Service/HttpService.cs
remove `IsPortInUse`, leave the port duplication problem for user to care of.
fixes #358
=> [OneBot] HttpService: remove port detection related code

Lagrange.Core/Internal/Service/System/FetchUserInfoService.cs
fix #349 
用户生日可能为非法值，创建DateTime报错
生日获取到的值年，月，日都可能出现0值
=> fix: get user birthday error

Lagrange.Core/Internal/Context/Logic/Implementation/WtExchangeLogic.cs, Lagrange.OneBot/LagrangeApp.cs
fix #417 #375 
部分用户在首次启动程序时，在未登录成功前与SSO Server断开连接，导致后续登录成功原因变为BotOnlineEvent.OnlineReason.Reconnect，即便登陆成功也无法正常启动ws服务
=> fix: 登录成功后ws服务未正常启动

Lagrange.Core/Message/Entity/RecordEntity.cs
修复该Issue中的问题：
https://github.com/LagrangeDev/Lagrange.Core/issues/450
修复因提前关闭AudioStream导致访问AudioSize属性时的System.ObjectDisposedException
=> [Core] Fixed accessing a closed Stream while posting record entity

README.md, README_zh.md
Because runkit.com doesn't seem to be working somewhere.
Perhaps you'd prefer something like the following
=> [Doc] Change Telegram's Badge

Lagrange.Core/Message/Entity/MultiMsgEntity.cs
To ensure consistency with other IMessageEntity classes, programs developed with Core can directly use the constructor to initialize MultiMsgEntity objects.
=> [Core]Change the access level of MultiMsgEntity's constructor to public

Lagrange.OneBot/LagrangeAppBuilder.cs, Lagrange.OneBot/Resources/appsettings.json, Lagrange.OneBot/Utility/OneBotSigner.cs
Only Http, Not support https and socks5 (so f**king ms)
=> [OneBot] Support Sign Http Proxy And Exposing Builder Ctor

Lagrange.Core/Common/Entity/BotFileEntry.cs
Now all operations on group files use FileId
Setting the field permission to internal is unreasonable
=> [Core] public file id

Lagrange.Core/Common/Interface/Api/OperationExt.cs, Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs, Lagrange.Core/Internal/Event/Message/GetC2cMessageEvent.cs, Lagrange.Core/Internal/Packets/Message/Action/SsoGetC2cMsg.cs, Lagrange.Core/Internal/Packets/Message/Action/SsoGetC2cMsgResponse.cs, Lagrange.Core/Internal/Packets/Message/ContentHead.cs, Lagrange.Core/Internal/Packets/Message/Element/Implementation/SourceMsg.PbPreserve.cs, Lagrange.Core/Internal/Service/Message/GetC2cMessageService.cs, Lagrange.Core/Message/Entity/ForwardEntity.cs, Lagrange.Core/Message/MessageChain.cs, Lagrange.Core/Message/MessagePacker.cs, Lagrange.OneBot/Database/MessageRecord.cs, Lagrange.OneBot/Message/Entity/ReplySegment.cs
- New API: GetC2CMessage; Retrieve historical messages through the sequence of private chat messages
- Fix #272; However, the private messages sent by the bot have not been stored in the database, only the error of Reply Id being 0 has been fixed, and now the correct message id will be displayed
- Fix the issue where replies to private messages cannot locate the original message
=> [All] new api - GetC2CMessage; fix multiple errors

Lagrange.Core/Common/Interface/Api/OperationExt.cs, Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
When using only Lagrange.Core, the Sequence member of MessageResult has its set accessor marked as internal, making it impossible to recall messages using only Sequence. Therefore, I have added an API that allows message recall by Sequence.
=> [Core]Recall the group message by sequence.

Lagrange.Core/Internal/Context/Logic/Implementation/MessagingLogic.cs
The missing image URL in #594 is due to this issue
=> [Core] Fix only the first message in the forwarded message has an image url

Lagrange.Core/Internal/Service/System/FetchMembersService.cs, Lagrange.OneBot/Core/Entity/Action/Response/OneBotGetMessageResponse.cs
Test time:
1. Fixed datetime to timestamp conversion in `OneBotGetMessageResponse`.
Wrong:
Fixed:
2. Fixed timestamp to datetime conversion in `FetchMembersService`.
Wrong:
Fixed:
=> [fix] Fixed conversion between timestamp and datetime

Lagrange.OneBot/Core/Operation/Group/GetGroupHonorInfoOperation.cs
fix #675 
It works on my machine!
=> [OneBot] Making API `get_group_honor_info` returns Onebot11 compliant

Lagrange.Core/Common/Interface/Api/OperationExt.cs, Lagrange.Core/Event/EventArg/PinChangedEvent.cs, Lagrange.Core/Event/EventInvoker.Events.cs, Lagrange.Core/Event/EventInvoker.cs, Lagrange.Core/Internal/Context/Logic/Implementation/MessagingLogic.cs, Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs, Lagrange.Core/Internal/Event/Action/FetchPinsEvent.cs, Lagrange.Core/Internal/Event/Action/SetPinFriendEvent.cs, Lagrange.Core/Internal/Event/Action/SetPinGroupEvent.cs, Lagrange.Core/Internal/Event/Notify/SysPinChangedEvent.cs, Lagrange.Core/Internal/Packets/Message/Notify/FriendDeleteOrPinChanged.cs, Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp0x5D6_1.cs, Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp0x5D6_18.cs, Lagrange.Core/Internal/Packets/Service/Oidb/Response/OidbSvcTrpcTcp0x12B3_0Response.cs, Lagrange.Core/Internal/Service/Action/FetchPinsService.cs, Lagrange.Core/Internal/Service/Action/SetPinFriendService.cs, Lagrange.Core/Internal/Service/Action/SetPinGroupService.cs, Lagrange.Core/Internal/Service/Message/PushMessageService.cs
Co-authored-by: Decrabbityyy <99632363+Decrabbityyy@users.noreply.github.com>
=> [Core] supported pin crd

Lagrange.Core/BotContext.cs, Lagrange.Core/Common/BotAppInfo.cs, Lagrange.Core/Common/Interface/BotFactory.cs, Lagrange.OneBot/LagrangeAppBuilder.cs
提供对自定义 `BotAppInfo` 的支持。具体更改如下：
- 在 Lagrange.Core 的 `BotFactory` 类中增加了两个包含 `BotAppInfo` 的静态方法；
- 在 Lagrange.OneBot 的初始化逻辑中增加了检测 `custom_appinfo.json` 是否存在的逻辑。若存在，则解析之，并将其中的 `BotAppInfo` 用于 `BotContext` 的初始化。
对原有的 API 及功能无影响。
=> [All] add support for custom `BotAppInfo`

Lagrange.Core/Message/Entity/XmlEntity.cs, Lagrange.Core/Message/MessageBuilder.cs, Lagrange.OneBot/Message/Entity/XmlSegment.cs
=> [All] Expanded XmlEntity and XmlSegment

Lagrange.OneBot/Core/Network/Service/HttpService.cs
https://github.com/botuniverse/onebot-11/blob/d4456ee706f9ada9c2dfde56a2bcfc69752600e4/communication/http.md?plain=1#L41
所有的POST content-type不支持都应该返回406，所以哪怕遇到lgr无法处理的，也应该返回406
=> [OneBot] Adjusting HTTP code to OneBot standards

Lagrange.Core/Utility/Network/Icmp.cs
Under some special OS env (such as docker container), may throw exception below:
```
Unhandled exception. System.PlatformNotSupportedException: The system's ping utility could not be found.
at System.Net.NetworkInformation.Ping.GetPingProcess(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
at System.Net.NetworkInformation.Ping.SendPingAsyncInternal[TArg](TArg getAddressArg, Func`3 getAddress, Int32 timeout, Byte[] buffer, PingOptions options, CancellationToken cancellationToken)
at Lagrange.Core.Utility.Network.Icmp.PingAsync(Uri hostIp, Int32 timeout)
at Lagrange.Core.Internal.Context.SocketContext.OptimumServer(Boolean requestMsf, …
```
=> Fix 'System.PlatformNotSupportedException'

Lagrange.Core/Internal/Packets/Message/Notify/GroupChange.cs, Lagrange.Core/Internal/Service/Message/PushMessageService.cs
=> [Core] fix operator in kick event

Lagrange.Core/Common/Interface/Api/GroupExt.cs
根据上下文猜测，SetFriendRequest 的 request 的类型可能写错了
=> [Core] 修复 SetFriendRequest 参数类型错误

Lagrange.Core/Internal/Context/HighwayContext.cs, Lagrange.Core/Internal/Context/Logic/Implementation/MessagingLogic.cs, Lagrange.Core/Internal/Context/Uploader/IHighwayUploader.cs, Lagrange.Core/Internal/Context/Uploader/ImageUploader.cs, Lagrange.Core/Internal/Context/Uploader/PttUploader.cs, Lagrange.Core/Internal/Context/Uploader/VideoUploader.cs, Lagrange.Core/Internal/Event/Message/GetC2cMessageEvent.cs, Lagrange.Core/Internal/Packets/Message/Action/SsoGetC2cMsgResponse.cs, Lagrange.Core/Internal/Packets/Message/Action/SsoGetGroupMsgResponse.cs, Lagrange.Core/Internal/Service/Message/GetC2cMessageService.cs, Lagrange.Core/Internal/Service/Message/GetGroupMessageService.cs, Lagrange.Core/Message/Entity/ForwardEntity.cs, Lagrange.Core/Message/IMessageEntity.cs, Lagrange.Core/Message/MessagePacker.cs, Lagrange.Core/Utility/Extension/ProtoExt.cs
1. Fix ForwardEntity in MultiEntity displays an exception
2. Fix ForwardEntity in MultiEntity has extra `not null` text after it
3. Allow using NTV2RichMedia in ForwardEntity in MultiMsg
=> [Core] Fixed various issues
