LagrangeDev/Lagrange.Core

- Lagrange.Core/Common/Interface/Api/OperationExt.cs
> [Api Name Change] FetMembers => FetchMembers

- Lagrange.OneBot/Lagrange.OneBot.csproj
- Lagrange.OneBot/Utility/QrCodeHelper.cs
This PR brings these advantages:
- reduce the qrcode size in the console (1/2 size)
- smaller library dependency
> Better qrcode generator

- Lagrange.OneBot/Core/Network/Service/ForwardWSService.cs
没找到正向ws的AccessToken代码, 自己糊了一个上去
解决一个ws连接断开后还会尝试往ws发消息的bug
> ForwardWS feat/fix

- Lagrange.OneBot/Core/Operation/Info/GetGroupMemberInfoOperation.cs
- Lagrange.OneBot/Core/Operation/Info/GetGroupMemberListOperation.cs
> fix permission in group member info

- Lagrange.OneBot/Core/Network/Service/ReverseWSService.cs
close https://github.com/LagrangeDev/Lagrange.Core/issues/67
> 反向ws兼容host直接配置协议

- Lagrange.Core/Internal/Context/Logic/Implementation/WtExchangeLogic.cs
- Lagrange.OneBot/Core/Message/Entity/AtSegment.cs
Fix #83
By the way, I removed the extra parenthesis from WtExchangeLogic.cs (I hope that parenthesis was redundant).
> [OneBot] Fix the situation where "Mention All" but there is no text

- Docker.md
add tips on Docker usage, correct path errors in commands.
> add docker tips,and fix path error

- .github/workflows/Lagrange.OneBot-build.yml
Added support for the Alpine Linux runtime to ensure compatibility with Alpine Docker containers.
> Add support for Alpine Linux runtime environment

- Lagrange.OneBot/LagrangeAppBuilder.cs
Source: compiled by telegram group members without modifying the directory ConfigPath in the default git configuration file.
Note: First time writing C#, please don't scold me (humble)
> [OneBot] Ensure that the parent folder of the files in the custom configuration exists

- Lagrange.OneBot/Core/Network/Options/ForwardHttpServiceOptions.cs
- Lagrange.OneBot/Core/Network/Options/HttpServiceOptions.cs
- Lagrange.OneBot/Core/Network/Options/ReverseHttpServiceOptions.cs
- Lagrange.OneBot/Core/Network/Service/DefaultLagrangeWebServiceFactory.cs
- Lagrange.OneBot/Core/Network/Service/ForwardHttpService.cs
- Lagrange.OneBot/Core/Network/Service/ForwardHttpServiceFactory.cs
- Lagrange.OneBot/Core/Network/Service/ReverseHttpService.cs
- Lagrange.OneBot/Core/Network/Service/ReverseHttpServiceFactory.cs
- Lagrange.OneBot/LagrangeAppBuilder.cs
Forward/Reverse HTTP communication implemented
> feat: support http

- .github/workflows/Lagrange.Core-nuget-push.yml
- .github/workflows/Lagrange.OneBot-build.yml
- .github/workflows/Lagrange.OneBot-docker-push.yml
- .github/workflows/Lagrange.OneBot-release.yml
- Lagrange.Core/Lagrange.Core.csproj
Maybe there shouldn't be any problem
> [Chroe] Refactor workflows

- Lagrange.OneBot/Core/Network/Service/HttpService.cs
> [OneBot] Revert `[OneBot] Fixed HTTP json post`

- Lagrange.OneBot/Core/Network/Options/ReverseWSServiceOptions.cs
- Lagrange.OneBot/Core/Network/Service/ForwardWSService.cs
- Lagrange.OneBot/Core/Network/Service/ReverseWSService.cs
> [OneBot] Support non-universal ws communication

- Lagrange.OneBot/LagrangeApp.cs
- Lagrange.OneBot/Resources/appsettings.json
- Lagrange.OneBot/Utility/QrCodeHelper.cs
Adds compatibility mode to console QrCode.
Normal mode:
Compatibility mode:
(Set `QrCode.ConsoleCompatibilityMode` to `true` in `appsettings.json`)
> [Onebot] Adds compatibility mode to console QrCode.

- Lagrange.OneBot/Core/Network/LagrangeWebSvcCollection.cs
> fix[ws]ignore due to connection closed

- Lagrange.OneBot/Core/Entity/Message/OneBotGroupMsg.cs
- Lagrange.OneBot/Core/Entity/Message/OneBotPrivateMsg.cs
- Lagrange.OneBot/Message/MessageService.cs
> [OneBot] Add raw_message for StringPost

- Lagrange.OneBot/Core/Network/Service/ForwardWSService.cs
> [OneBot] Fix ws blocking on abnormal close

- Lagrange.OneBot/Core/Notify/NotifyService.cs
fix #174 
[Onebot 11 文档](https://github.com/botuniverse/onebot-11/blob/master/event/notice.md#%E7%BE%A4%E7%A6%81%E8%A8%80)
> [OneBot] Fix GroupMuteEvent sub_type

- Lagrange.OneBot/Core/Operation/File/GroupFSOperations.cs
- Lagrange.OneBot/Core/Operation/Generic/FetchCustomFaceOperation.cs
Fix the retcode of `fetch_custom_face`.
Fix the code indentation in `QrCodeHelper.cs`.
> [Onebot] Fix the retcode of `fetch_custom_face` and `get_group_root_files`.

- .github/workflows/Lagrange.Core-nuget-push.yml
@Executor-Cheng says this file doesn't affect packaging.
> [Chore] Remove LICENSE trigger from Nuget push workflow

- .github/workflows/Lagrange.Core-nuget-push.yml
Reverts LagrangeDev/Lagrange.Core#185
My mistake.
> Revert "[Chore] Remove LICENSE trigger from Nuget push workflow"

- README.md
- README_zh.md
Co-authored-by: KusaGumina <kaitoazyazy@gmail.com>
> [Chore] Add banner to README

- Lagrange.Core/Internal/Packets/Message/Component/Extra/ImageExtra.cs
- Lagrange.Core/Message/Entity/ImageEntity.cs
> [Core] Fix CommonElem image url

- Lagrange.OneBot/Core/Entity/OneBotFakeNode.cs
> [OneBot] Support obv11 format fake node

- Lagrange.OneBot/Core/Operation/Message/GetForwardMsgOperation.cs
- Lagrange.OneBot/Core/Operation/Message/SendForwardMessageOperation.cs
> [OneBot] Fix empty nickname in /get_forward_msg

- Lagrange.OneBot/Core/Entity/Message/OneBotFriendMsgHistory.cs
- Lagrange.OneBot/Core/Operation/Message/GetFriendMessageHistoryOperation.cs
> Fix `get_friend_msg_history` parameter `count` is not effective (#212)

- Docker.md
- Docker_zh.md
> [Doc] Fixing some bugs in Docker.md

- Lagrange.OneBot/Core/Network/Service/ReverseWSService.cs
Adjust buffer size growth logic. When buffer size < 8192, the buffer will grow 2x each time, otherwise, 4096B each time.
Truncate logging for excessive long message, limit to 1024 characters.
> [OneBot] ReverseWS improvement

- Lagrange.OneBot/Core/Network/Service/ReverseWSService.cs
Fix #232 
Fix #228 
Programs offered by Executor-Cheng
> [OneBot] WebSocket accepts data too slowly (#232) (#228)

- Lagrange.OneBot/Core/Operation/Group/GetGroupHonorInfoOperation.cs
- Lagrange.OneBot/Core/Operation/Info/GetStatusOperation.cs
> [OneBot] Fix returning incorrect retcode

- Lagrange.Core/Common/Entity/BotGroupRequest.cs
- Lagrange.OneBot/Core/Notify/NotifyService.cs
> Fix `group_decrease` missing `operator_id` (#238)

- Lagrange.OneBot/Core/Network/Service/ForwardWSService.cs
- Lagrange.OneBot/Lagrange.OneBot.csproj
> [OneBot] refactoring FowardWSService.cs

- Lagrange.OneBot/Core/Network/Service/ReverseWSService.cs
- Correct client role
- Favor `ReconnectInterval`
> [OneBot] ws related minor fix

- Lagrange.Core/Internal/Context/Logic/Implementation/CachingLogic.cs
- Lagrange.OneBot/Core/Notify/NotifyService.cs
> [Core] Fix warning when kicking out Bot (#255)

- Lagrange.Core/Event/EventArg/GroupMemberIncreaseEvent.cs
- Lagrange.Core/Internal/Service/Message/PushMessageService.cs
> [Core] Fix wrong type in GroupMemberIncreaseNotice

- README.md
- README_zh.md
> [Doc] README Add a warning

- Lagrange.OneBot/Core/Operation/Message/GetMessageOperation.cs
> [OneBot] Incorrect `sender` for `get_msg`

- Lagrange.OneBot/Core/Network/Service/ReverseWSService.cs
> [OneBot] fix rws close

- Lagrange.Core/Message/Entity/FileEntity.cs
- Lagrange.Core/Message/Entity/ForwardEntity.cs
- Lagrange.Core/Message/Entity/ImageEntity.cs
- Lagrange.Core/Message/Entity/MentionEntity.cs
- Lagrange.Core/Message/Entity/MultiMsgEntity.cs
- Lagrange.Core/Message/Entity/RecordEntity.cs
- Lagrange.Core/Message/Entity/TextEntity.cs
- Lagrange.Core/Message/Entity/VideoEntity.cs
- Lagrange.Core/Message/IMessageEntity.cs
- Lagrange.Core/Message/MessageChain.cs
> [Core]: Fix multimsg desc & count

- Lagrange.OneBot/Core/Network/Service/HttpService.cs
- Exception handling
- Logging
- Minor refactor
- Allow passing access_token in query string
> [OneBot] HttpService minor tweaks

- Lagrange.OneBot/Core/Network/Service/HttpService.cs
> [OneBot] Fix http data string escape

- Lagrange.OneBot/Core/Network/Service/ForwardWSService.cs
Optimized based on the suggestions from the senior expert
> [OneBot] Optimize ForwardWebSocket

- Lagrange.Core/Internal/Packets/Message/Element/Implementation/MarketFace.cs
- Lagrange.Core/Message/Entity/MarketFaceEntity.cs
- Lagrange.OneBot/Message/Entity/MarketFaceSegment.cs
Messages can be sent successfully at the moment
But PC can't display images without cache
> [All] Support MarketFace (semi-manufactured goods)

- Lagrange.OneBot/Core/Operation/Group/GetGroupHonorInfoOperation.cs
- Lagrange.OneBot/Core/Operation/Group/SetGroupSpecialTitleOperation.cs
- Lagrange.OneBot/Core/Operation/Info/GetStrangerInfoOperation.cs
- Lagrange.OneBot/Core/Operation/Message/FriendPokeOperation.cs
- Lagrange.OneBot/Core/Operation/Message/GroupPokeOperation.cs
- Lagrange.OneBot/Core/Operation/Request/SetFriendAddRequestOperation.cs
- Lagrange.OneBot/Core/Operation/Request/SetGroupAddRequestOperation.cs
> [OneBot] Relax json deserialization on more operations

- Lagrange.OneBot/Core/Network/Service/ForwardWSService.cs
> Fix /api 接口仍旧有 event 上报 #359

- Lagrange.OneBot/Core/Network/Service/ForwardWSService.cs
> [OneBot] Add timeout handling for disconnect operations

- Lagrange.OneBot/Message/Entity/RecordSegment.cs
> [OneBot] Record stream not closed

- Lagrange.Core/Message/Entity/ForwardEntity.cs
> [OneBot] Fix mention is ignored

- Lagrange.OneBot/Core/Network/Service/HttpService.cs
fixes #377, additionally close the response on exception.
> Fix HttpService Content-Type Parse

- Lagrange.Core/Internal/Packets/Message/Element/Elem.cs
- Lagrange.Core/Internal/Packets/Message/Element/Implementation/Marketface.cs
- Lagrange.Core/Message/Entity/MarketfaceEntity.cs
- Lagrange.Core/Message/MessageBuilder.cs
- Lagrange.OneBot/Message/Entity/MfaceSegment.cs
Synchronized data format after discussion with @linyuchen
> [All] Sync Mface

- Lagrange.OneBot/LagrangeApp.cs
- Lagrange.OneBot/LagrangeAppBuilder.cs
- Lagrange.OneBot/Message/Entity/MusicSegment.cs
- Lagrange.OneBot/Resources/appsettings.json
- Lagrange.OneBot/Utility/MusicSigner.cs
> [OneBot] Implemented Music Custom Sign Server

- Lagrange.OneBot/Core/Network/Service/HttpPostService.cs
- Lagrange.OneBot/Core/Network/Service/HttpService.cs
- Lagrange.OneBot/Core/Network/Service/ReverseWSService.cs
> [OneBot] fix(logging): better logging message

- Lagrange.OneBot/Message/Entity/RecordSegment.cs
- Lagrange.OneBot/Utility/AudioHelper.cs
At first it was just to fix the bug where voice doesn't show the time
> [OneBot] Refactoring RecordSegment

- Lagrange.Core/Event/EventArg/GroupEssenceEvent.cs
- Lagrange.Core/Event/EventInvoker.Events.cs
- Lagrange.Core/Event/EventInvoker.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/MessagingLogic.cs
- Lagrange.Core/Internal/Event/Notify/GroupSysEssenceEvent.cs
- Lagrange.Core/Internal/Packets/Message/Notify/GroupEssenceMessage.cs
- Lagrange.Core/Internal/Packets/Message/Notify/NotifyMessageBody.cs
- Lagrange.Core/Internal/Service/Message/PushMessageService.cs
- Lagrange.OneBot/Core/Entity/Notify/OneBotGroupEssence.cs
- Lagrange.OneBot/Core/Notify/NotifyService.cs
Refactor & Fix Core GroupEssenceEvent and  Implemented OneBot GroupEssenceEvent
> [All] Implemented GroupEssenceEvent

- .github/workflows/Lagrange.OneBot-build.yml
- .github/workflows/Lagrange.OneBot-release.yml
> [Chore] Change the name of the artifact

- Lagrange.Core/Common/Interface/Api/GroupExt.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
- Lagrange.Core/Internal/Event/Action/GroupSetBotEvent.cs
- Lagrange.Core/Internal/Event/Action/GroupSetBothdEvent.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp0x112E_1.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp0x907D_1.cs
- Lagrange.Core/Internal/Service/Action/GroupSetBotService.cs
- Lagrange.Core/Internal/Service/Action/GroupSetBothdService.cs
- Lagrange.OneBot/Core/Entity/Action/OneBotSetGroupBot.cs
- Lagrange.OneBot/Core/Entity/Action/OneBotSetGroupBothd.cs
- Lagrange.OneBot/Core/Operation/Group/SetGroupBotOperation.cs
- Lagrange.OneBot/Core/Operation/Group/SetGroupBothdOperation.cs
Co-authored-by: sisi0318 <gamemode12345@163.com>
> 支持设置群bot发言状态

- Lagrange.OneBot/Core/Network/Service/ForwardWSService.cs
and fixed a `context1` naming problem caused by someone.
> [OneBot] Fix tcp not being closed when websocket is closed on Linux

- Lagrange.Core/Common/Interface/Api/GroupExt.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
- Lagrange.Core/Internal/Event/Action/GroupSetBothdEvent.cs
- Lagrange.Core/Internal/Service/Action/GroupSetBothdService.cs
- Lagrange.OneBot/Core/Entity/Action/OneBotSetGroupBothd.cs
- Lagrange.OneBot/Core/Operation/Group/SetGroupBothdOperation.cs
> [All] Add data(key) to SGBh

- Lagrange.Core/Utility/Sign/SignProvider.cs
resolve https://github.com/LagrangeDev/Lagrange.Core/issues/503#issuecomment-2292606994
> [Core] add `OidbSvcTrpcTcp.0x6d9_4` to WhiteListCommand

- Lagrange.OneBot/Core/Notify/NotifyService.cs
- Lagrange.OneBot/LagrangeAppBuilder.cs
The first indexing of the old database will load the entire database into memory.
Please restart Lagrange.Core after it is completed
> [Core] database add indexed

- Lagrange.Core/Common/Entity/BotGroupClockInResult.cs
- Lagrange.Core/Common/Interface/Api/OperationExt.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
- Lagrange.Core/Internal/Event/Action/GroupClockInEvent.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp0xEB7_1.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Response/OidbSvcTrpcTcp0xEB7_1Response.cs
- Lagrange.Core/Internal/Service/Action/GroupClockInService.cs
有几个问题
1. 这个包似乎不需要sign都能用，就没加`SignProvider`的`WhiteListCommand`，要加吗
2. `OidbSvcTrpcTcp0xEB7_1` 这个包的第三个字段(AppVersion)，实测不加也不会影响结果，要删吗
> [Core] Group clock in 群打卡

- Lagrange.Core/Common/Interface/Api/GroupExt.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
- Lagrange.Core/Internal/Event/Action/GroupFSCreateFolderEvent.cs
- Lagrange.Core/Internal/Event/Action/GroupFSDeleteFolderEvent.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp0x6D7_0.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp0x6D7_1.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Response/OidbSvcTrpcTcp0x6D7Response.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Response/OidbSvcTrpcTcp0x6D7_0Response.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Response/OidbSvcTrpcTcp0x6D7_1Response.cs
- Lagrange.Core/Internal/Service/Action/GroupFSDeleteFolderService.cs
- Lagrange.OneBot/Core/Entity/Action/OneBotDeleteFolder.cs
- Lagrange.OneBot/Core/Operation/File/GroupFSOperations.cs
> [All] Add DeleteGroupFolderOp & adjust CreateGroupFolderOp

- Lagrange.OneBot/Utility/OneBotSigner.cs
I cant believe(add onebot defeat sign url)
> [Onebot] fix first start need input signserver

- Lagrange.Core/Common/Interface/Api/GroupExt.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
- Lagrange.Core/Internal/Event/Action/GroupFSListEvent.cs
- Lagrange.Core/Internal/Service/Action/GroupFSViewService.cs
> [All] Add pagination to FetchGroupFSList

- Lagrange.Core/Internal/Service/Message/GroupFSUploadService.cs
> [Core] Fix #565

- Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp0x10C0_2.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Response/OidbSvcTrpcTcp0x10C0Response.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Response/OidbSvcTrpcTcp0x10C0_1_2Response.cs
- Lagrange.Core/Internal/Service/System/FetchFilteredGroupRequestsService.cs
- Lagrange.Core/Internal/Service/System/FetchGroupRequestsService.cs
> [Core] Fetch the filtered requests simultaneously in FetchGroupRequests

- Lagrange.OneBot/LagrangeAppBuilder.cs
> [OneBot]Add api for configure Logging

- Lagrange.Core/Message/Entity/MentionEntity.cs
数据样本：
[0000383C0AB5700A4F088DEAB5BE0E12187.txt](https://github.com/user-attachments/files/16920323/0000383C0AB5700A4F088DEAB5BE0E12187.txt)
不知道 PbReserve 干啥用的就保留了
> Fix UIN exception when processing long markdown text messages

- Lagrange.Core/Common/Entity/BotGroupRequest.cs
- Lagrange.Core/Common/Interface/Api/GroupExt.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
- Lagrange.Core/Internal/Event/Action/SetGroupFilteredRequestEvent.cs
- Lagrange.Core/Internal/Event/System/FetchGroupRequestsEvent.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp0x10C8.cs
- Lagrange.Core/Internal/Service/Action/SetGroupFilteredRequestService.cs
- Lagrange.Core/Internal/Service/System/FetchFilteredGroupRequestsService.cs
- Lagrange.Core/Internal/Service/System/FetchGroupRequestsService.cs
- Lagrange.OneBot/Core/Entity/Action/OneBotSetRequest.cs
- Lagrange.OneBot/Core/Notify/NotifyService.cs
- Lagrange.OneBot/Core/Operation/Request/SetGroupAddRequestOperation.cs
> [All] Support refuse reason & handle filtered request in GroupRequest

- Lagrange.OneBot/LagrangeAppBuilder.cs
- Add a judgment on whether an index exists or not
- Force a restart of the program when indexed for the first time
- fix database memory leak
- [GetGroupMessageHistoryOperation.cs#L24](https://github.com/LagrangeDev/Lagrange.Core/blob/ce7e3ddd55e8ef209fb05b73b6a93e84672b8f7a/Lagrange.OneBot/Core/Operation/Message/GetGroupMessageHistoryOperation.cs#L24)
- [GetFriendMessageHistoryOperation.cs#L24](https://github.com/LagrangeDev/Lagrange.Core/blob/ce7e3ddd55e8ef209fb05b73b6a93e84672b8f7a/Lagrange.OneBot/Core/Operation/Message/GetFriendMessageHistoryOperation.cs#L24)
> [OneBot] About database

- Lagrange.Core/Internal/Context/Logic/Implementation/MessagingLogic.cs
- Lagrange.Core/Message/Entity/ForwardEntity.cs
- Lagrange.Core/Message/Entity/MentionEntity.cs
- Lagrange.Core/Message/MessageFilter.cs
- Lagrange.Core/Message/MessagePacker.cs
- Move `MessageFilter` to [`MessageingLogic@Incoming`](https://github.com/LagrangeDev/Lagrange.Core/blob/2b83478bce294d641ed6d94d0c2f4cf93401f117/Lagrange.Core/Internal/Context/Logic/Implementation/MessagingLogic.cs#L46)
- Allow add custom rules to remove multiple entities
- `MessageFilter` add `ImageEntity` filter (fix #548), add `ForwardEntity` filter (fix #611)
> [Core] About MessageFilter

- Lagrange.Core/Internal/Service/Message/PushMessageService.cs
- Lagrange.Core/Utility/Binary/Tlv/TlvPacker.cs
- Lagrange.Core/Utility/Crypto/TeaImpl.cs
- Lagrange.Core/Utility/Sign/LinuxSigner.cs
- Lagrange.Core/Utility/Sign/MacSigner.cs
- Lagrange.Core/Utility/Sign/UrlSigner.cs
- Lagrange.Core/Utility/Sign/WindowsSigner.cs
These prints should only be used during Debug
> [Core] Kill `Console.WriteLine` and update internal signer implementation

- Lagrange.Core/Internal/Service/System/FetchUserInfoService.cs
> [Core] fix no custom status info

- Lagrange.Core/Event/EventArg/GroupTodoEvent.cs
- Lagrange.Core/Event/EventInvoker.Events.cs
- Lagrange.Core/Event/EventInvoker.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/MessagingLogic.cs
- Lagrange.Core/Internal/Event/Notify/GroupSysTodoEvent.cs
- Lagrange.Core/Internal/Service/Message/PushMessageService.cs
Maybe the todo is set by determining `await bot.GetGroupTodo(...).Retcode` is `10004` (recall)
> [Core] Support todo events

- Lagrange.Core/Common/Interface/Api/BotExt.cs
- Lagrange.Core/Common/Interface/Api/GroupExt.cs
- Lagrange.Core/Common/Interface/Api/OperationExt.cs
- Lagrange.Core/Internal/Context/BusinessContext.cs
- Lagrange.Core/Internal/Context/HighwayContext.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/CachingLogic.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/MessagingLogic.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/WtExchangeLogic.cs
- Lagrange.Core/Internal/Context/Logic/LogicBase.cs
- Lagrange.Core/Internal/Context/PacketContext.cs
- Lagrange.Core/Internal/Context/SocketContext.cs
- Lagrange.Core/Internal/Context/Uploader/Common.cs
- Lagrange.Core/Internal/Context/Uploader/FileUploader.cs
- Lagrange.Core/Internal/Context/Uploader/IHighwayUploader.cs
- Lagrange.Core/Internal/Context/Uploader/ImageUploader.cs
- Lagrange.Core/Internal/Context/Uploader/PttUploader.cs
- Lagrange.Core/Internal/Context/Uploader/VideoUploader.cs
- Lagrange.Core/Internal/Network/ClientListener.cs
- Lagrange.Core/Utility/Network/Http.cs
- Lagrange.OneBot/Core/Notify/NotifyService.cs
- Lagrange.OneBot/Core/Operation/Ability/UploadImageOperation.cs
- Lagrange.OneBot/Core/Operation/Generic/SendPacketOperation.cs
- Lagrange.OneBot/Core/Operation/Message/SendForwardMessageOperation.cs
- Lagrange.OneBot/Core/Operation/Request/SetFriendAddRequestOperation.cs
- Lagrange.OneBot/Core/Operation/Request/SetGroupAddRequestOperation.cs
This reverts commit d015386e4b431dde324e79dd8caba18c1139ac79.
> Revert "feat: Make all API cancellable (#630)"

- Lagrange.Core/Common/Entity/ImageOcrResultEntry.cs
- Lagrange.Core/Common/Interface/Api/OperationExt.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
- Lagrange.Core/Internal/Event/Action/ImageOcrEvent.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp.0xE07_0.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Response/OidbSvcTrpcTcp0xE07_0Response.cs
- Lagrange.Core/Internal/Service/Action/ImageOcrService.cs
- Lagrange.OneBot/Core/Entity/Action/OneBotOcrImage.cs
- Lagrange.OneBot/Core/Operation/Ability/UploadImageOperation.cs
- Lagrange.OneBot/Core/Operation/Generic/OcrImageOperation.cs
> [All] ImageOcr

- Lagrange.OneBot/Core/Entity/Common/LightApp.cs
- Lagrange.OneBot/Core/Operation/Converters/AutosizeConverter.cs
- Lagrange.OneBot/Core/Operation/Converters/ForwardConverter.cs
- Lagrange.OneBot/Core/Operation/Converters/NullIfEmptyConverter.cs
- Lagrange.OneBot/Message/Entity/LocationSegment.cs
> [OneBot] Better LightApp parse

- Lagrange.OneBot/Message/Entity/PokeSegment.cs
https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E6%88%B3%E4%B8%80%E6%88%B3
> [OneBot] Better PokeSegment Compatibility

- Lagrange.Core/Common/Interface/Api/OperationExt.cs
- Lagrange.Core/Internal/Context/Logic/Implementation/OperationLogic.cs
- Lagrange.Core/Internal/Event/Action/DeleteFriendEvent.cs
- Lagrange.Core/Internal/Packets/Service/Oidb/Request/OidbSvcTrpcTcp0x126B_0.cs
- Lagrange.Core/Internal/Service/Action/DeleteFriendService.cs
- Lagrange.OneBot/Core/Entity/Action/OneBotDeleteFriend.cs
- Lagrange.OneBot/Core/Operation/Generic/DeleteFriendOperation.cs
> [All] feat: implemented delete friend

- Lagrange.OneBot/Core/Entity/Message/OneBotGroupMsg.cs
- Lagrange.OneBot/Core/Entity/Message/OneBotPrivateMsg.cs
- Lagrange.OneBot/Core/Entity/OneBotEntityBase.cs
- Lagrange.OneBot/Message/MessageService.cs
> [Onebot] Fixed message time in `get_xxx_msg_history`.

- Lagrange.Core/Internal/Packets/Message/Action/LongMsgResult.cs
- Lagrange.Core/Internal/Service/Message/MultiMsgDownloadService.cs
- Lagrange.Core/Internal/Service/Message/MultiMsgUploadService.cs
- Lagrange.Core/Message/Filter/MessageFilter.cs
- Lagrange.Core/Message/Filter/Rule/MultiMsgTrailingXmlFilterRule.cs
1. Fixed the problem of redundant messages when getting nested forwarded messages
2. Fix the problem of MultiMsgEntity followed by XmlEntity
> [All] Various fixes

- .github/workflows/Lagrange.OneBot-build.yml
- .github/workflows/Lagrange.OneBot-release.yml
- Lagrange.OneBot/Resources/Dockerfile
- Lagrange.OneBot/Resources/docker-entrypoint.sh
Fix #756 
musl is no longer supported, because [realm-dotnet](https://github.com/realm/realm-dotnet) has [issues](https://github.com/realm/realm-dotnet/issues/2847) with musl support and musl is not widely used
> [Docker] Fix #756 

- Lagrange.OneBot/Program.cs
> [OneBot] Add Banner

- Lagrange.Core/Internal/Context/HighwayContext.cs
- Lagrange.Core/Internal/Packets/SsoPacker.cs
- Lagrange.Core/Internal/Service/Message/PushMessageService.cs
- Lagrange.Core/Message/Entity/FileEntity.cs
- Lagrange.Core/Message/Entity/JsonEntity.cs
- Lagrange.Core/Message/Entity/LightAppEntity.cs
- Lagrange.Core/Message/Entity/XmlEntity.cs
- Lagrange.Core/Utility/Binary/BinaryPacket.cs
- Lagrange.Core/Utility/Binary/Compression/Common.cs
- Lagrange.Core/Utility/Binary/Compression/ZCompression.cs
> [Core] 去掉一些多余的内存分配

- Lagrange.OneBot/Resources/Dockerfile
- Lagrange.OneBot/Updater/GithubUpdater.cs
> [fix] Disable AutoUpdater in docker

- README.md
- README_zh.md
Fix Lagrange.OneBot document URL.
> [Update] README, fix #853
